# Generated by Django 3.0.5 on 2020-05-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0002_route_route_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='elevation_gain',
            field=models.IntegerField(default=0),
        ),
    ]
